cc_library(
    name = "greet",
    srcs = [
        "greet.cc"
    ],
    hdrs = [
        "greet.h",
    ],
    includes = [
        ".",
    ],
    visibility = [
        "//visibility:public",
    ],
)